// utils/getMuscleFromName.ts

const EXERCISE_MUSCLE_MAP: Record<string, string> = {
  press_banca: "pecho",
  press_mancuernas: "pecho",
  press_inclinado_mancuernas: "pecho",
  aperturas_mancuernas: "pecho",
  flexiones: "pecho",
  flexiones_diamante: "pecho",
  press_bandas: "pecho",
  dominadas: "espalda",
  remo_barra: "espalda",
  remo_mancuernas: "espalda",
  jalon_al_pecho: "espalda",
  remo_bandas: "espalda",
  pullover_mancuerna: "espalda",
  press_militar: "hombros",
  press_hombro_mancuernas: "hombros",
  elevaciones_laterales: "hombros",
  elevaciones_frontales: "hombros",
  elevaciones_bandas: "hombros",
  pike_pushups: "hombros",
  curl_barra: "biceps",
  curl_mancuernas: "biceps",
  curl_martillo: "biceps",
  curl_bandas: "biceps",
  chinups: "biceps",
  fondos_triceps: "triceps",
  extension_triceps_mancuerna: "triceps",
  extension_triceps_polea: "triceps",
  patada_triceps: "triceps",
  extension_triceps_bandas: "triceps",
  sentadilla: "piernas",
  sentadilla_goblet: "piernas",
  prensa: "piernas",
  peso_muerto_rumano: "piernas",
  zancadas: "piernas",
  sentadilla_bandas: "piernas",
  extension_cuadriceps: "piernas",
  curl_femoral: "piernas",
  elevacion_talones: "piernas",
  hip_thrust: "gluteos",
  puente_gluteos: "gluteos",
  patada_gluteo_bandas: "gluteos",
  patada_gluteo_polea: "gluteos",
  crunch_abdominal: "core",
  plancha: "core",
  elevaciones_piernas: "core",
  rueda_abdominal: "core",
  crunch_bandas: "core",
};

export function getMuscleFromName(exerciseName: string): string {
  return EXERCISE_MUSCLE_MAP[exerciseName.toLowerCase()] ?? "";
}
